version: "3.8"

services:
    # PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: translation-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - translation-network

    # MySQL Service
    db:
        image: mysql:8.0
        container_name: translation-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - translation-network

    # Nginx Service
    nginx:
        image: nginx:alpine
        container_name: translation-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - translation-network

networks:
    translation-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
